git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" init 
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" commit -m "initial commit" 
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "groups/CSRtier2support.group" "roles/DirectorProductManagement.role" "roles/TechnicalWriter.role"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "groups/Reviewers.group" "roles/SWEngineer.role" "roles/SWDevManager.role"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "roles/VPDevelopment.role" "roles/RecruitingManager.role" "groups/Publishers648751.group"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "roles/CEO.role" "roles/ProductManager.role" "groups/editor.group"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "roles/VPHumanResources.role" "roles/DirectorQA.role" "roles/Publisher.role"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "roles/Recruiter.role" "roles/CustomerSupportRepresentative.role" "roles/QAEngineer.role"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "scontrols/ajax__deployDeveloperAJT_apexrunner.scf" "scontrols/ajax__deployDeveloperAJT_editorscript.scf" "aura/aurang__template"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "scontrols/ajax__deployDeveloperAJT_codepress.scf" "components/modal.component" "scontrols/ajax__deployDeveloperAJT_loading.scf"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "components/SiteHeader.component" "scontrols/ajax__deployDeveloperAJT_docs.scf" "scontrols/ajax__deployDeveloperAJT_perf.scf"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "scontrols/SLX__About_Change_Control.scf" "components/SiteLogin.component" "scontrols/ajax__deployDeveloperAJT_tab.scf"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "aura/aurang__configureRegion" "components/SiteFooter.component" "scontrols/ajax__deployDeveloperAJT_uisamples.scf"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "aura/aurang__regionDemo" "components/importvisualstrap.component" "scontrols/ajax__deployDeveloperAJT_template.scf"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "scontrols/ajax__deployDeveloperAJT_editor.scf" "components/knowledgeHeader.component" "aura/aurang__demoComponent"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "scontrols/ajax__deployDeveloperAJT_main.scf" "components/zipEntry.component" "components/panel.component"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "components/RemoteTK.component" "scontrols/ajax__deployDeveloperAJT_demo.scf" "scontrols/ajax__deployDeveloperAJT_debugshell.scf"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "components/knowledgePagination.component" "scontrols/ajax__deployDeveloperAJT_samples.scf" "components/MissionDetail.component"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "components/pageheader.component" "scontrols/ajax__deployDeveloperAJT_explorer.scf" "aura/aurang__regionDemoApp"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "components/unzip.component" "components/SitePoweredBy.component" "components/visualstrapblock.component"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "components/knowledgeFooter.component" "components/glyph.component" "components/zip.component"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "aura/aurang__region" "scontrols/ajax__deployDeveloperAJT_txsamples.scf" "components/knowledgeCategories.component"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "pages/MyFate3.page" "pages/sidzdatecheck.page" "queues/InternationalLeads.queue"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "pages/metadata.page" "pages/ForgotPasswordConfirm.page" "pages/sampleVisual.page"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "pages/VFpage1.page" "pages/InMaintenance.page" "pages/JqueryXMLMenu.page"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "pages/S1FaceItGameCapture.page" "pages/Template.page" "pages/VFP_AngularBootstrapTemplate.page"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "queues/PartnerRelations.queue" "pages/Exception.page" "pages/Mission.page"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "pages/sampleVisual_case.page" "pages/Player.page" "pages/ApexCodeCoverageList.page"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "pages/MyFate1.page" "pages/SiteTemplate.page" "pages/SiteLogin.page"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "pages/VFP_Sid_AdminUtilities.page" "pages/includePage.page" "queues/USLeads.queue"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "pages/JqueryTextToSpeech.page" "pages/VFP_Sid_Admin_ComponentSelector.page" "pages/MobileSample_jQueryMobile.page"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "pages/knowledgeLayout.page" "queues/USSilverBronze.queue" "pages/GameList.page"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "pages/dependenttest_1.page" "pages/VFP_Sid_Admin_FieldAdoptionUtility.page" "pages/StdExceptionTemplate.page"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "queues/UnclaimedPositionsQueue.queue" "pages/CandidateMap.page" "pages/MissionList.page"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "pages/xmltest.page" "pages/Standings.page" "pages/knowledgeProduct.page"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "pages/knowledgeSearch.page" "pages/S1FaceItIndex.page" "pages/AutomatedTestSetup.page"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "queues/USEscalations.queue" "pages/metadatadata.page" "queues/InternationalPlatinumGold.queue"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "pages/Unauthorized.page" "pages/GodBlessMe.page" "pages/knowledgeHome.page"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "pages/SiteRegisterConfirm.page" "pages/dependenttest.page" "pages/SiteRegister.page"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "pages/VFP_AuthorizeEnvironment.page" "pages/StringToXML.page" "pages/VFP_Sid_Admin_RegisterEnvironments.page"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "pages/BandwidthExceeded.page" "pages/PDFTest.page" "pages/metadataretrieve.page"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "pages/MyFate.page" "queues/Publishers.queue" "pages/TableSort.page"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "queues/USPlatinumGold.queue" "pages/knowledgeCss.page" "pages/VFP_Sid_Admin_ListViewAnalyzer.page"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "pages/CAPTCHA.page" "pages/SidzKnowledgePage.page" "pages/ValidateOauth.page"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "pages/VFP_TestCanvas.page" "pages/ComponentSearch.page" "pages/metadatadeploy.page"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "pages/PaginationTest.page" "pages/S1FaceItAbout.page" "pages/S1FaceItCamera.page"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "pages/Controller_check.page" "pages/VFP_JSFORCEUPDATEPLAY.page" "pages/FileNotFound.page"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "queues/InternationalEscalations.queue" "pages/Start_Here.page" "pages/metadatabrowser.page"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "pages/SimplePage.page" "pages/IdeasHome.page" "queues/InternationalSilverBronze.queue"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "pages/CloudSpokeChallenge_GenerateDocx.page" "pages/UnderConstruction.page" "pages/ChangePassword.page"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "pages/ViewTISCases.page" "pages/S1FaceItGame.page" "queues/CSRs.queue"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "pages/sidzplay.page" "pages/AccountSampleVF.page" "pages/ForgotPassword.page"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "pages/knowledgePKBSiteSetupHelp.page" "pages/SidzImplementations.page" "pages/S1FaceIt.page"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "objects/Game__c.object" "objects/Test_Runner_Job__c.object" "objects/Employment_Website__c.object"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "objects/Facebook_Connection_Settings__c.object" "objects/child1__c.object" "objects/TIS_Detail__c.object"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "objects/Cloud_Hunter_Settings__c.object" "objects/Job_Posting__c.object" "reportTypes/reportsmy.reportType"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "reportTypes/report1.reportType" "objects/SLX__Change_Object__c.object" "objects/My_Article__c.object"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "objects/Master_Two__c.object" "objects/Developer__kav.object" "objects/faceIt__c.object"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "objects/Expense__c.object" "objects/Achievement__c.object" "objects/Player__c.object"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "objects/Environment__c.object" "objects/PKBSiteSetup__c.object" "objects/ChatUser__c.object"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "objects/SLX__Change_Control__c.object" "objects/Console__c.object" "objects/Backup__c.object"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "objects/Repository__c.object" "objects/Place__c.object" "objects/Org__c.object"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "objects/parent__c.object" "objects/Position__c.object" "objects/Job_Application__c.object"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "objects/Junction_One_and_Two__c.object" "objects/Mission__c.object" "objects/Automated_Test_Run__c.object"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "objects/Outside_Collection__kav.object" "objects/PracticeSample__c.object" "objects/ChatUserContact__c.object"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "objects/ChatTransmission__c.object" "objects/Review__c.object" "objects/Candidate__c.object"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "objects/Father__c.object" "objects/File_Attachments__c.object" "objects/Son__c.object"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "objects/TIS_Summary__c.object" "objects/Master_One__c.object" "applications/Recruiting.app"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "applications/Practice.app" "applications/Sample_console_app.app" "applications/standard__Service.app"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "applications/bFO_Management.app" "applications/Swagg_Customer_Support_Application.app" "applications/standard__Chatter.app"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "applications/standard__Platform.app" "applications/standard__Community.app" "applications/standard__Sales.app"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "applications/standard__Sites.app" "applications/standard__Content.app" "applications/standard__Marketing.app"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "applications/cloudconverter__Cloud_Converter.app" "applications/Lightning.app" "applications/Sid_s_Admin_Utilities.app"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "applications/SLX__ChangeControl.app" "applications/Cloud_Hunter.app" "applications/standard__AppLauncher.app"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "applications/Force_com.app" "applications/ajax__AJAXTools.app" "applications/Automated_Testing.app"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "tabs/jQuery_Mobile.tab" "tabs/Sid_s_Admin_Home.tab" "tabs/PracticeSample__c.tab"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "tabs/Org__c.tab" "tabs/FaceIt.tab" "tabs/Start_Here.tab"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "tabs/cloudconverter__Cloud_Converter.tab" "tabs/PKBSiteSetup__c.tab" "tabs/Repository__c.tab"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "tabs/Father__c.tab" "tabs/Mission__c.tab" "tabs/Console__c.tab"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "tabs/MetadataRetrieveDemo.tab" "tabs/Player__c.tab" "tabs/child1__c.tab"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "tabs/Master_One__c.tab" "tabs/MetadataDeployDemo.tab" "tabs/Master_Two__c.tab"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "tabs/Automated_Test_Run__c.tab" "tabs/Automated_Test_Setup.tab" "tabs/SLX__AboutChangeControl.tab"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "quickActions/UpdateStatus.quickAction" "quickActions/EditDescription.quickAction" "quickActions/Defer.quickAction"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "tabs/Son__c.tab" "tabs/Position__c.tab" "tabs/Environment__c.tab"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "tabs/Junction_One_and_Two__c.tab" "tabs/Game__c.tab" "tabs/Achievement__c.tab"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "tabs/Backup__c.tab" "tabs/Job_Application__c.tab" "tabs/My_Article__c.tab"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "tabs/ChatUser__c.tab" "tabs/ajax__AJAXTools.tab" "quickActions/UpdatePriority.quickAction"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "tabs/Expense__c.tab" "tabs/Candidate__c.tab" "tabs/Employment_Website__c.tab"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "tabs/parent__c.tab" "quickActions/create_cqse_action.quickAction" "tabs/SLX__Change_Control__c.tab"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "tabs/Place__c.tab" "tabs/MetadataBrowser.tab" "layouts/Asset-Asset Layout.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/Case-Case %28Sales%29 Layout.layout" "layouts/Solution-Solution Layout.layout" "layouts/Contract-Contract Layout.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/Case-Case %28Marketing%29 Layout.layout" "layouts/Case-Case %28Support%29 Layout.layout" "layouts/Employment_Website__c-Employment Website Layout.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/Game__c-Game Layout.layout" "layouts/Contact-Contact Layout.layout" "layouts/Candidate__c-Candidate Layout.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/CaseClose-Close Case Layout.layout" "layouts/My_Article__c-My Article Layout.layout" "layouts/Junction_One_and_Two__c-Junction One and Two Layout.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/Player__c-Player Layout.layout" "layouts/Contact-Contact %28Support%29 Layout.layout" "layouts/Contact-Contact %28Marketing%29 Layout.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/Test_Runner_Job__c-Test Runner Job Layout.layout" "layouts/ContentVersion-General.layout" "layouts/My_Article__c-Final_Publisher.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/My_Article__c-Changed to Published.layout" "layouts/File_Attachments__c-File Attachment Layout.layout" "layouts/Task-Task Layout.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/Event-Event Layout.layout" "layouts/PracticeSample__c-PracticeSample Layout.layout" "layouts/Automated_Test_Run__c-Automated Test Run Layout.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/Opportunity-Opportunity %28Support%29 Layout.layout" "layouts/Product2-Product Layout.layout" "layouts/Position__c-Position Layout.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/Repository__c-Repository Layout.layout" "layouts/Developer__kav-Developer Layout.layout" "layouts/Lead-Lead %28Marketing%29 Layout.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/Org__c-Org Layout.layout" "layouts/ChatTransmission__c-ChatTransmission Layout.layout" "layouts/Son__c-Son Layout.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/Outside_Collection__kav-Outside Collection Layout.layout" "layouts/Opportunity-Opportunity %28Marketing%29 Layout.layout" "layouts/Case-Case Layout.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/CampaignMember-Campaign Member Page Layout.layout" "layouts/ChatUserContact__c-ChatUserContact Layout.layout" "layouts/Place__c-Place Layout.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/Idea-Idea Layout.layout" "layouts/TIS_Summary__c-TIS Summary Layout.layout" "layouts/SLX__Change_Object__c-Change Object Layout.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/Account-Account %28Marketing%29 Layout.layout" "layouts/Backup__c-Backup Layout.layout" "layouts/Console__c-Console Layout.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/ChatUser__c-ChatUser Layout.layout" "layouts/Opportunity-Opportunity %28Sales%29 Layout.layout" "layouts/SLX__Change_Control__c-Change Control Layout - Submitters.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/Father__c-Father Layout.layout" "layouts/Campaign-Campaign Layout.layout" "layouts/Environment__c-Environment Layout.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/Lead-Lead Layout.layout" "layouts/Achievement__c-Achievements Layout.layout" "layouts/parent__c-parent Layout.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/Master_Two__c-Master Two Layout.layout" "layouts/QuoteLineItem-Quote Line Item Layout.layout" "layouts/Job_Posting__c-Job Posting Layout.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/Review__c-Review Layout.layout" "layouts/Lead-Lead %28Support%29 Layout.layout" "layouts/Quote-Quote Layout.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/PKBSiteSetup__c-PKB Site Setup Layout.layout" "layouts/Mission__c-Mission Layout.layout" "layouts/SLX__Change_Control__c-Change Control Layout.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/Account-Account %28Support%29 Layout.layout" "layouts/OpportunityLineItem-Opportunity Product Layout.layout" "layouts/User-User Layout.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/Lead-Lead %28Sales%29 Layout.layout" "layouts/TIS_Detail__c-TIS Detail Layout.layout" "layouts/Contact-Contact %28Sales%29 Layout.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/Account-Account %28Sales%29 Layout.layout" "layouts/Master_One__c-Master One Layout.layout" "layouts/Opportunity-Opportunity Layout.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/Expense__c-Expense Layout.layout" "layouts/child1__c-child1 Layout.layout" "layouts/My_Article__c-NO Edit.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/Job_Application__c-Job Application Layout.layout" "layouts/Account-Account Layout.layout" "installedPackages/SLX.installedPackage"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "staticresources/pkb_image_insertYourLogo.resource" "staticresources/jQuery.resource" "staticresources/Shyama.resource"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "staticresources/pkb_image_tabs_sprite.resource" "staticresources/xmltest.resource" "staticresources/pkb_image_bgBottom.resource"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "staticresources/SFSmartStorePlugin.resource" "staticresources/uigrid.resource" "staticresources/BatchApex.resource"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "staticresources/SiteSamples.resource" "staticresources/pkb_js_base.resource" "staticresources/VisualStrap_Resources.resource"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "staticresources/MissionIcons.resource" "installedPackages/cloudconverter.installedPackage" "installedPackages/ajax.installedPackage"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "staticresources/jszip.resource" "staticresources/FACEIT.resource" "staticresources/pkb_image_companyLogo.resource"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "staticresources/SyntaxHighlighter.resource" "staticresources/pkb_image_columnBg.resource" "staticresources/MobileSample_Resources_jQueryMobile.resource"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "staticresources/SFHybridAppJs.resource" "staticresources/pkb_image_bannerBg.resource" "staticresources/JqueryMenu.resource"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "staticresources/pkb_image_searchBoxBg.resource" "staticresources/reports.resource" "staticresources/PhoneGap1_8_1_iOS.resource"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "staticresources/jSignature.resource" "staticresources/pkb_image_imagine.resource" "staticresources/CloudHunterImages.resource"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "staticresources/SFHybridAppCss.resource" "staticresources/extjs.resource" "staticresources/pkb_js_prototype.resource"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "staticresources/JSforce.resource" "staticresources/pkb_image_fullWidthBg.resource" "staticresources/pkb_css_reset.resource"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "staticresources/pkb_image_resultBg.resource" "staticresources/cloudtunes.resource" "staticresources/CCCClientLibraries.resource"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "staticresources/aurang__auraNgLogo.resource" "staticresources/hybrid_smartstore.resource" "staticresources/pkb_image_leftPanelBg.resource"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "staticresources/gameListCSS.resource" "staticresources/Jqueryold.resource" "staticresources/pkb_image_filterPanelBg.resource"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "staticresources/Callingmethod.resource" "staticresources/JqueryTextToSpeech.resource" "staticresources/PhoneGap1_8_1_Android.resource"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "staticresources/BarCodeScanneriOS.resource" "installedPackages/aurang.installedPackage" "staticresources/hybrid_offline.resource"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "staticresources/JSRender.resource" "staticresources/testcss.resource" "staticresources/sampledocx.resource"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "staticresources/cloudHunter_CSS.resource" "staticresources/pkb_image_tab.resource" "staticresources/BarCodeScannerAndroid.resource"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "staticresources/aurang__angularjs.resource" "staticresources/pkb_image_bgMenu.resource" "staticresources/pkb_image_poweredBySfdc.resource"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "staticresources/pkb_image_bg.resource" "approvalProcesses/Position__c.ASDASDASD.approvalProcess" "approvalProcesses/My_Article__c.My_Article_Approval_Process.approvalProcess"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "approvalProcesses/Position__c.ADD.approvalProcess" "Workflow/SLX__Change_Control__c.workflow" "Workflow/Master_One__c.workflow"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "Workflow/Mission__c.workflow" "Workflow/Outside_Collection__kav.workflow" "Workflow/Junction_One_and_Two__c.workflow"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "Workflow/Repository__c.workflow" "Workflow/Backup__c.workflow" "Workflow/File_Attachments__c.workflow"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "Workflow/Developer__kav.workflow" "Workflow/Org__c.workflow" "Workflow/Console__c.workflow"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "Workflow/Player__c.workflow" "Workflow/Game__c.workflow" "Workflow/Place__c.workflow"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "Workflow/child1__c.workflow" "Workflow/ChatTransmission__c.workflow" "Workflow/Review__c.workflow"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "Workflow/TIS_Detail__c.workflow" "Workflow/My_Article__c.workflow" "Workflow/PracticeSample__c.workflow"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "Workflow/ChatUserContact__c.workflow" "Workflow/Employment_Website__c.workflow" "Workflow/Expense__c.workflow"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "Workflow/TIS_Summary__c.workflow" "Workflow/Facebook_Connection_Settings__c.workflow" "Workflow/Job_Application__c.workflow"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "Workflow/faceIt__c.workflow" "Workflow/Job_Posting__c.workflow" "Workflow/Son__c.workflow"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "Workflow/PKBSiteSetup__c.workflow" "Workflow/Master_Two__c.workflow" "Workflow/Environment__c.workflow"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "Workflow/Father__c.workflow" "Workflow/parent__c.workflow" "Workflow/Automated_Test_Run__c.workflow"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "flows/sample-1.flow" "Workflow/Test_Runner_Job__c.workflow" "Workflow/Cloud_Hunter_Settings__c.workflow"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "Workflow/Position__c.workflow" "Workflow/Candidate__c.workflow" "Workflow/Achievement__c.workflow"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "Workflow/ChatUser__c.workflow" "Workflow/SLX__Change_Object__c.workflow" "translations/de.translation"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "translations/en_US.translation" "homePageLayouts/DE Default.homePageLayout" "callCenters/DemoAdapter.callCenter"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "connectedApps/mysalesforce.connectedApp" "connectedApps/Authorize_bFO_Environments.connectedApp" "connectedApps/Local_App.connectedApp"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "connectedApps/My_Hybrid_App.connectedApp" "connectedApps/sfmetadatabackup.connectedApp" "communities/Internal Community.community"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "connectedApps/django_canvas.connectedApp" "connectedApps/sfadmin.connectedApp" "connectedApps/finalattempt.connectedApp"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "connectedApps/DjangoOauthTest.connectedApp" "connectedApps/bFO_backup.connectedApp" "sharingRules/TIS_Detail__c.sharingRules"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "sharingRules/parent__c.sharingRules" "sharingRules/Master_One__c.sharingRules" "sharingRules/File_Attachments__c.sharingRules"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "sharingRules/Game__c.sharingRules" "sharingRules/ChatUser__c.sharingRules" "sharingRules/PracticeSample__c.sharingRules"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "sharingRules/TIS_Summary__c.sharingRules" "sharingRules/Backup__c.sharingRules" "sharingRules/Repository__c.sharingRules"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "sharingRules/ChatTransmission__c.sharingRules" "sharingRules/SLX__Change_Control__c.sharingRules" "sharingRules/Environment__c.sharingRules"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "sharingRules/My_Article__c.sharingRules" "sharingRules/Employment_Website__c.sharingRules" "sharingRules/Place__c.sharingRules"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "sharingRules/Cloud_Hunter_Settings__c.sharingRules" "sharingRules/Expense__c.sharingRules" "sharingRules/Candidate__c.sharingRules"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "sharingRules/Console__c.sharingRules" "sharingRules/Job_Application__c.sharingRules" "sharingRules/Father__c.sharingRules"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "sharingRules/Automated_Test_Run__c.sharingRules" "sharingRules/faceIt__c.sharingRules" "sharingRules/Position__c.sharingRules"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "sharingRules/Master_Two__c.sharingRules" "sharingRules/Facebook_Connection_Settings__c.sharingRules" "sharingRules/Org__c.sharingRules"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "sharingRules/PKBSiteSetup__c.sharingRules" "sites/Authorize_Environments.site" "remoteSiteSettings/myorg.remoteSite"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "remoteSiteSettings/recaptcha.remoteSite" "remoteSiteSettings/Devswagg.remoteSite" "remoteSiteSettings/personal.remoteSite"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "permissionsets/Sid_s_Admin_Utilities_Developer.permissionset" "remoteSiteSettings/myip.remoteSite" "remoteSiteSettings/schneiderelectric_1.remoteSite"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "remoteSiteSettings/ApexDevNet.remoteSite" "remoteSiteSettings/schneiderelectric.remoteSite" "remoteSiteSettings/metadata.remoteSite"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "permissionsets/Sample_console_app_Developer.permissionset" "remoteSiteSettings/OPSservice.remoteSite" "remoteSiteSettings/postbin.remoteSite"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "profiles/editor.profile" "classes/TestController.cls" "classes/ObjectComparator.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "profiles/Chatter Free User.profile" "classes/IllegalArgumentException.cls" "classes/HelloWorldTrigger.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/TestExtensionOne.cls" "classes/UnsupportedObjectTypeException.cls" "classes/IntegerRangeTest.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/HTMLEncoder.cls" "classes/TestTISMethods.cls" "classes/StopWatchTest.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/ArrayUtilsTest.cls" "classes/ObjectPaginator.cls" "classes/RandomStringUtilsTest.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/UrlUtilsTest.cls" "profiles/MarketingProfile.profile" "classes/StringBuffer.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/ArrayUtils.cls" "classes/NumberUtilsTest.cls" "profiles/Force%2Ecom - Free User.profile"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/StickyParametersController.cls" "triggers/AfterUserInsert.trigger" "classes/StaticVariables.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "triggers/BeforeInsert.trigger" "classes/faceIt.cls" "profiles/Recruiter.profile"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/CharacterTest.cls" "triggers/ContactbeforeInsert.trigger" "classes/LanguageUtilsTest.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/TestConstants.cls" "classes/GameListController.cls" "triggers/AccountbeforeInsert.trigger"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/WordUtils.cls" "classes/FluentHTMLTest.cls" "triggers/HelloTrigger.trigger"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/faceIt_Test.cls" "classes/TestRunner.cls" "classes/SObjectPaginator.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/SetCondition.cls" "classes/ObjectPaginatorTest.cls" "classes/SetUtilsTest.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/RemoteUtils.cls" "classes/ShrutiApex.cls" "classes/StandingsControllerTests.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/RandomUtilsTest.cls" "profiles/Standard.profile" "classes/SObjectPaginatorTest.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/DateFormula.cls" "classes/UserUtils.cls" "classes/RandomUtils.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/JSONUtils.cls" "classes/AutomatedTestSetup_Controller.cls" "classes/TestRunner_Test.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/SetConditionTest.cls" "classes/StickyParametersControllerTest.cls" "classes/KnowledgeControllerTest.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/MetadataServiceTest.cls" "classes/ObjectPaginatorListenerForTesting.cls" "classes/MetadataController.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/OrConditionTest.cls" "classes/SelectOptionComparatorTest.cls" "classes/LongRange.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/Field.cls" "classes/NumberFormatException.cls" "classes/SObjectPaginatorListenerForTesting.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/SiteLoginController.cls" "classes/ApexCodeCoverageList_Con.cls" "classes/sidzplay.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/SoqlUtilsTest.cls" "classes/DoubleRangeTest.cls" "classes/DateFormulaTest.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/StaticClassSid.cls" "classes/CTest.cls" "classes/AJTSample2.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/DecimalRangeComparatorTest.cls" "classes/StopWatch.cls" "classes/MetadataRetrieveController.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "triggers/CaseTISSummary.trigger" "classes/XMLDom.cls" "classes/TestUtils.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/GameListControllerTests.cls" "classes/HttpUtils.cls" "profiles/PlatformPortal.profile"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/BooleanUtilsTest.cls" "profiles/Partner Community Login User.profile" "classes/MetadataService.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/Character.cls" "classes/reCAPTCHA.cls" "classes/FieldCondition.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/SoqlBuilder.cls" "classes/NumberUtils.cls" "profiles/Admin.profile"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/StringUtils.cls" "classes/PlayerControllerExtension.cls" "classes/MissionListControllerTests.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/WS_OPSProductService.cls" "classes/ApexCodeCoverageList_Con_Mock_Generator.cls" "classes/SiteRegisterController.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "profiles/Cross Org Data Proxy User.profile" "classes/TestRunnerResults.cls" "classes/CaseTISControllerExtension.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/PlayerValidationTests.cls" "classes/HttpUtilsTest.cls" "classes/NotCondition.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/WordUtilsTest.cls" "classes/LanguageUtils.cls" "triggers/parentbeforetrigger.trigger"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "profiles/ReadOnly.profile" "profiles/Customer Community Login User.profile" "classes/ChangePasswordController.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/ForgotPasswordController.cls" "classes/MetadataCreateJobTest.cls" "classes/SoqlOptionsTest.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "profiles/HighVolumePortal.profile" "classes/TestClass.cls" "classes/DoubleRange.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/IntegrationIface.cls" "classes/DecimalRange.cls" "classes/DecimalRangeComparator.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/ConditionGroupTest.cls" "classes/MetadataCreateJob.cls" "classes/superSort.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "profiles/Authorize Environments Profile.profile" "classes/MapUtilsTest.cls" "classes/MyController.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "profiles/Chatter Moderator User.profile" "classes/SmartFactory.cls" "classes/SObjectSortByFieldComparatorTest.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/SObjectSortByNameComparator.cls" "classes/PageUtils.cls" "profiles/reviewer.profile"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/tableSort.cls" "profiles/CustomerManager.profile" "classes/TestUtilsTest.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "profiles/Custom%3A Sales Profile.profile" "classes/SelectOptionWrapper.cls" "classes/RandomStringUtils.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/JSONUtilsTest.cls" "classes/FieldConditionTest.cls" "classes/bridgefrontofficeSchneiderElectricCom.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/PlayerControllerExtensionTests.cls" "classes/MyHttp.cls" "classes/MissionControllerExtension.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/FieldTest.cls" "classes/SObjectSortByNameComparatorTest.cls" "classes/LongRangeTest.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/sidplayswithcode.cls" "classes/SoqlUtils.cls" "profiles/Custom%3A Support Profile.profile"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/SetUtils.cls" "classes/KnowledgeController.cls" "classes/SimpleApexClassAJT.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/StringUtils2Test.cls" "classes/MissionValidationTests.cls" "classes/UrlUtils.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/MetadataDataController.cls" "classes/MissionControllerExtensionTests.cls" "classes/SystemUtils.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/RemoteTKController.cls" "profiles/Partner Community User.profile" "classes/SystemUtilsTest.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/ObjectPaginatorListener.cls" "classes/SoqlOptions.cls" "classes/amxSci02Provisioning.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/Sidz.cls" "classes/FluentHTML.cls" "classes/FacebookRegistrationHandler.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/BooleanUtils.cls" "classes/StandingsController.cls" "classes/MapUtils.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/MyTestClass.cls" "classes/CreateTIS.cls" "classes/SidzDateCheckController.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/ISObjectComparator.cls" "triggers/contactAfterInsert.trigger" "classes/PrimitiveComparator.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/TestClass1.cls" "classes/ApexCodeCoverageList_Con_Test.cls" "classes/OrCondition.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/IllegalStateException.cls" "classes/PageUtilsTest.cls" "classes/IntegerRange.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/UserUtilsTest.cls" "classes/SObjectSortByFieldComparator.cls" "classes/MissionListController.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "profiles/SolutionManager.profile" "profiles/Customer Community User.profile" "classes/IdentityUtils.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/MetadataDeployController.cls" "classes/EmailUtils.cls" "profiles/Interface.profile"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/SObjectUtils.cls" "classes/Condition.cls" "classes/StringBufferTest.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/UnitOfTime.cls" "profiles/Chatter External User.profile" "profiles/publisher.profile"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/AndConditionTest.cls" "profiles/Swagg Customer Support Representative.profile" "classes/HTMLEncoderTest.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/PlaceValidationTests.cls" "classes/startHereController.cls" "classes/Operator.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/ValidateOauth.cls" "classes/EmailUtilsTest.cls" "classes/SObjectUtilsTest.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/DatabaseUtilsTest.cls" "classes/IntegrationImpl.cls" "classes/SelectOptionComparator.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/serviceFirethornBizProvisionservice.cls" "classes/TestRemoteTKController.cls" "classes/AndCondition.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/dataListCon.cls" "classes/MetadataServicePatcher.cls" "classes/SObjectPaginatorListener.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/SmartFactory_Test.cls" "profiles/Hiring Manager.profile" "classes/DecimalRangeTest.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "profiles/ContractManager.profile" "classes/Soqlable.cls" "classes/MetadataServiceExamples.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/InvalidCharacterStringException.cls" "classes/VFTalkieController.cls" "profiles/StandardAul.profile"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "profiles/Custom%3A Marketing Profile.profile" "classes/SoqlBuilderTest.cls" "triggers/CaseTISDetail.trigger"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/StringUtilsTest.cls" "classes/SObjectComparator.cls" "classes/AchievementValidationTests.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/IndexOutOfBoundsException.cls" "classes/OrderBy.cls" "classes/OrderByTest.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "profiles/Partner.profile" "triggers/MyCaseTrigger.trigger" "classes/NotConditionTest.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/ConditionGroup.cls" "classes/DatabaseUtils.cls" "classes/PrimitiveComparatorTest.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "profiles/CSR tier 2 customer support.profile" "profiles/Guest.profile" "profiles/Standard Employee.profile"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "classes/AP24_EmailToApex.cls" "classes/MyFirstClass.cls" "classes/NestableCondition.cls"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" commit --author="siddharatha nagavarapu<siddharatha nagavarapu@schneider-electric.com>" -m "siddharatha nagavarapu s commit"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "quickActions/NewContact.quickAction" "quickActions/NewChildCase.quickAction" "quickActions/NewCase.quickAction"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "quickActions/NewGroupMember.quickAction" "quickActions/NewEvent.quickAction" "quickActions/NewAccount.quickAction"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "quickActions/NewLead.quickAction" "quickActions/LogACall.quickAction" "quickActions/NewGroup.quickAction"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "quickActions/NewOpportunity.quickAction" "quickActions/NewTaskFromFeedItem.quickAction" "quickActions/NewGroupRecord.quickAction"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "quickActions/NewTask.quickAction" "quickActions/NewNote.quickAction" "layouts/Macro-Macro Layout.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/DuplicateRecordSet-Duplicate Record Set Layout.layout" "layouts/FeedItem-Feed Item Layout.layout" "layouts/Global-Global Layout.layout"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" commit --author="salesforce.com<salesforce.com@schneider-electric.com>" -m "salesforce.com s commit"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "layouts/Pricebook2-Price Book Layout.layout" "layouts/PricebookEntry-Price Book Entry Layout.layout" "installedPackages/sf_chttr_apps.installedPackage"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" add "installedPackages/sf_com_apps.installedPackage"
git --git-dir="../sidretrieve/.git" --work-tree="../sidretrieve" commit --author="Automated Process<Automated Process@schneider-electric.com>" -m "Automated Process s commit"
